; Generated by Mini C Compiler
section .text
    global _our_code

_our_code:
    mov eax, 10
    push eax
    mov eax, 2
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    push eax
    push eax
    mov eax, 4
    push eax
    mov ebx, eax
    pop eax
    add eax, ebx
    ret
