; Generated by Mini C Compiler
; Source: tests/e_undeclared.cmini
section .data
; Variables
    x dd 0

section .text
    global _our_code
    extern _print_int

_our_code:
    mov eax, 10
    mov dword [x], eax
    mov eax, 20
    mov dword [y], eax
    mov eax, dword [y]
    push eax
    call _print_int
    add esp, 4
    ret
