; Generated by Mini C Compiler
; Expression: 10*3-4
section .text
    global _our_code

_our_code:
    mov eax, 10
    push eax
    mov eax, 3
    mov ebx, eax
    pop eax
    imul eax, ebx
    push eax
    mov eax, 4
    mov ebx, eax
    pop eax
    sub eax, ebx
    ret
